### ISSUE TITLE
Kontrola úkolu 1-3.

### ISSUE THREAD

**Issue by Majko3030** [Majko3030/python-012021#1]
Mám ke kontrole úkoly 1-3. @andywaltlova

**Comment by andywaltlova** [comment]
### 1. úkol :heavy_check_mark: 
- Pěkné, program dělá co má
- ❗ Upozornění: pokud je proměnná typu bool, neměla by jsi psát `if promenna == True:` , preferovaná varianta je zkrátka napsat `if promenna:` , malý příklad:

```python
pravda = True
if pravda:
    print('Je to pravda!')
else:
    print('Neni to pravda!')'
```

Případně můžeš použít klíčové slovo `not`:
```python
pravda = True
if not pravda:  # negace False je True
    print('Neni to pravda!')
else:
    print('Je to pravda!')'
```

Je to stejné jako když kontroluješ například `if 2>3:` , což samozřejmě není pravda, ale za celým výrazem `2>3` si můžeš zkrátka představit `False` hodnotu :)

### 2. úkol :heavy_check_mark: 

- Super, splňuje zadání 
- Na posledním řádku tedy nevím proč máš print v uvozovkách, ale předpokládám že je to překlep nebo špatný komentář :-)
- 💡 Doporučení: při změně hodnoty proměnné je možné použít i kratší zápis, hlavně u delších názvů proměnných se to hodí
```python
sklad[typSoucastky] = sklad[typSoucastky]-mnozstvi
sklad[typSoucastky] -= mnozstvi
```

### 3. úkol :heavy_check_mark: 

- Perfektní, není co dodat :)

***

U prvního úkolu tě poprosím upravit kontrolu té bool hodnoty, stačí upravit až budeš odevzdávat další úkoly.
Celkově moc pěkné 👍 , kdyby jsi měla jakýkoli problém s dalšími úkoly, stačí mi sem napsat komentář :-)

**Comment by Majko3030** [comment]
úkoly 4 a 5 jsou ke kontrole , zpětnou vazbu se podívám a opravím

**Comment by Majko3030** [comment]
Úkol 2 - je to v úvozovkách, jako pro kontrolu (je to tam, když by tam bylo něco špatně), ale zároveň nechci, aby se to zobrazovalo jinému uživateli. 

Stejně v 5 jsem si tam hodila poznámku, kterou jsem se chtěla zeptat, a to zda jde nějak zjistit duplicity ve slovníku (já to v kodu udělala ručně), ale kdyby tam bylo hodně hodnot, tak to moje řešení nedává smysl. 

Také na to navazuje dotaz na vyhledání hodnoty dle klíče ve slovníku. Když jsem zadala "Zkus mě chytit", tak to našlo první hodnotu, tu druhou to ignoruje. Jde toto obejít, aby se načítaly oboje hodnoty, co mají stejný klíč?

**Comment by Majko3030** [comment]
úkol 1 je opravený, děkuju za vysvětlení  :D

**Comment by andywaltlova** [comment]
Pokud chceš mít nějaký kód, který je jen komentář - tedy nevykonává se skriptem. Kontrolní print je naprosto v pořádku, ale zvykem je to spíše zakomentovat pomocí `#`
```python
# jednoradkovy komentar
"""
Viceradkovy
ve dvojitych uvozovkach
"""
'''
Viceradkovy
v jednoduchych uvozovkach
'''
```

K tvému druhému dotazu, tak duplicitní klíče se ve slovníku nedají najít, zkrátka proto, že to jde proti logice toho, jak slovník funguje, pokud do něj někdo omylem vloží danou hodnotu znovu, tak se vždy ta předchozí přepíše -> vždy platí ta poslední, ta původní přestane existovat, tedy nedá se ani nijak najít.
```python
prodeje2020 = {
    "Zkus mě chytit": 3157,
    "Vrah zavolá v deset": 3541,
    "Vražda podle knihy": 2510,
    "Past": 2364,
    "Zločinný steh": 5412,
    "Zkus mě chytit": 6671,
}
print(prodeje2020["Zkus mě chytit"])
```
Většinou pokud například v cyklu přidáváš klíče, tak u toho musíš nějak sama ošetřit a určit, co se má stát pokud daný klíč už ve slovníku je (hodnoty sečíst, přepsat, vyhodit error apod.). Tady se to jirkovi povedlo zdvojit omylem přímo při vytvoření :)

### 4. úkol :heavy_check_mark: 

- Super, pěkné, chválím nápad přidat mezeru rovnou do slovníku (`mezera = str(' ')` toto ale nikde nepoužíváš, bohatě stačí mít mezeru jako `' '`, přesně tak jak to děláš na řádku 50, když mezeru vkládáš do slovníku)
- Ve for cyklu stačí mít `znak` místo `znak[0]`, v proměnné `znak` je vždy jen jedno písmeno, proto je v tomto případě index nula stejný jako celá proměnná

### 5. úkol :heavy_check_mark:

- Pěkné řešení :)
- 💡 Jenom upozornění k zamyšlení :
tvůj kód spoléhá na to, že všechny knihy které jsou v prvním slovníku, jsou i ve druhém (pokud by tomu tak nebylo, může se ti stát že na řádku 21 dostaneš KeyError, kvůli `prodeje2020[kniha]` ). 
Bezpečnejší cesta by byla mít dvě podmínky , jednu pro každý slovník (kontrola zda je kniha ve slovníku),číslo které ke knize najdeš pak přičíst do proměnné a na konci jen proměnnou vypsat:)

**Comment by andywaltlova** [comment]
Máš splněno, tedy zavírám issue, měl by ale stále jít komentovat :)
