### ISSUE TITLE
lekce 9

### ISSUE THREAD

**Issue by Majko3030** [Majko3030/python-012021#6]
Ahoj Andy,

úkoly k 9 lekci mám ke kontrole :)

Měj se hezky,

Denisa

**Comment by andywaltlova** [comment]
Ahoj ! 👋 

Super, všech 5 úkolů máš v pořádku ✔️ . Nemám k nim žádnou výtku 👍 

Momentálně máš **27b** - takže **ještě alepoň 6 na certifikát**. Staci tedy doplnit cokoli z tydnu 5,6,7,10,11 (Django mozna bude nejjednodusi protoze to mame ted cerstve v pameti 😉 )
